import asyncio
import os
from pathlib import Path
import base64

# Load environment variables from a .env file when present. This uses python-dotenv
# (listed in requirements.txt) but falls back gracefully if it's not installed.
try:
    from dotenv import load_dotenv

    load_dotenv()
except Exception:
    # If python-dotenv isn't available or loading fails, continue using existing env.
    pass

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

from mcp.client.session import ClientSession
from mcp.client.streamable_http import streamablehttp_client


async def main():
    base_url = os.getenv("TEST_MCP_URL", "http://127.0.0.1:8010/mcp")
    print(f"Connecting to {base_url}")

    async with streamablehttp_client(base_url) as (read, write, _):
        async with ClientSession(read, write) as session:
            await session.initialize()

            tools = await session.list_tools()
            tool_names = [t.name for t in tools.tools]
            print("tools:", tool_names)

            # 1) echo
            echo_res = await session.call_tool("echo", {"text": "hello"})
            print("echo:", echo_res)

            # 2) slack_post (requires tokens and a test channel)
            channel = os.getenv("TEST_SLACK_CHANNEL", "")
            if channel:
                post_res = await session.call_tool(
                    "slack_post", {"channel": channel, "text": "MCP test message"}
                )
                print("slack_post:", post_res)
            else:
                print("skip slack_post (no TEST_SLACK_CHANNEL)")

            # 3) slack_upload using base64 small PNG
            if channel:
                # tiny 1x1 PNG
                png_b64 = (
                    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII="
                )
                up_res = await session.call_tool(
                    "slack_upload",
                    {
                        "channel": channel,
                        "filename": "pixel.png",
                        "data_base64": png_b64,
                        "initial_comment": "MCP image test",
                    },
                )
                print("slack_upload (image):", up_res)
            else:
                print("skip slack_upload image (no TEST_SLACK_CHANNEL)")

            # 4) slack_upload using a generated local PDF via file_path
            if channel:
                pdf_path = Path("./_tmp_test_report.pdf")
                try:
                    c = canvas.Canvas(str(pdf_path), pagesize=letter)
                    c.drawString(72, 720, "CogniQuery MCP test PDF")
                    c.drawString(72, 700, "This is an autogenerated test file.")
                    c.showPage()
                    c.save()
                    up_pdf2 = await session.call_tool(
                        "slack_upload",
                        {
                            "channel": channel,
                            "filename": "report.pdf",
                            "file_path": str(pdf_path),
                            "initial_comment": "MCP pdf test via file_path",
                        },
                    )
                    print("slack_upload (pdf file_path):", up_pdf2)
                finally:
                    if pdf_path.exists():
                        try:
                            pdf_path.unlink()
                        except Exception:
                            pass
            else:
                print("skip slack_upload pdf (no TEST_SLACK_CHANNEL)")


if __name__ == "__main__":
    asyncio.run(main())
